
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `PageText` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PageText
 * 
 */
export type PageTextModel = runtime.Types.Result.DefaultSelection<Prisma.$PageTextPayload>

export type AggregatePageText = {
  _count: PageTextCountAggregateOutputType | null
  _min: PageTextMinAggregateOutputType | null
  _max: PageTextMaxAggregateOutputType | null
}

export type PageTextMinAggregateOutputType = {
  identifier: string | null
  text: string | null
}

export type PageTextMaxAggregateOutputType = {
  identifier: string | null
  text: string | null
}

export type PageTextCountAggregateOutputType = {
  identifier: number
  text: number
  _all: number
}


export type PageTextMinAggregateInputType = {
  identifier?: true
  text?: true
}

export type PageTextMaxAggregateInputType = {
  identifier?: true
  text?: true
}

export type PageTextCountAggregateInputType = {
  identifier?: true
  text?: true
  _all?: true
}

export type PageTextAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PageText to aggregate.
   */
  where?: Prisma.PageTextWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageTexts to fetch.
   */
  orderBy?: Prisma.PageTextOrderByWithRelationInput | Prisma.PageTextOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PageTextWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageTexts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageTexts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PageTexts
  **/
  _count?: true | PageTextCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PageTextMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PageTextMaxAggregateInputType
}

export type GetPageTextAggregateType<T extends PageTextAggregateArgs> = {
      [P in keyof T & keyof AggregatePageText]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePageText[P]>
    : Prisma.GetScalarType<T[P], AggregatePageText[P]>
}




export type PageTextGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PageTextWhereInput
  orderBy?: Prisma.PageTextOrderByWithAggregationInput | Prisma.PageTextOrderByWithAggregationInput[]
  by: Prisma.PageTextScalarFieldEnum[] | Prisma.PageTextScalarFieldEnum
  having?: Prisma.PageTextScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PageTextCountAggregateInputType | true
  _min?: PageTextMinAggregateInputType
  _max?: PageTextMaxAggregateInputType
}

export type PageTextGroupByOutputType = {
  identifier: string
  text: string
  _count: PageTextCountAggregateOutputType | null
  _min: PageTextMinAggregateOutputType | null
  _max: PageTextMaxAggregateOutputType | null
}

type GetPageTextGroupByPayload<T extends PageTextGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PageTextGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PageTextGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PageTextGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PageTextGroupByOutputType[P]>
      }
    >
  >



export type PageTextWhereInput = {
  AND?: Prisma.PageTextWhereInput | Prisma.PageTextWhereInput[]
  OR?: Prisma.PageTextWhereInput[]
  NOT?: Prisma.PageTextWhereInput | Prisma.PageTextWhereInput[]
  identifier?: Prisma.StringFilter<"PageText"> | string
  text?: Prisma.StringFilter<"PageText"> | string
}

export type PageTextOrderByWithRelationInput = {
  identifier?: Prisma.SortOrder
  text?: Prisma.SortOrder
}

export type PageTextWhereUniqueInput = Prisma.AtLeast<{
  identifier?: string
  AND?: Prisma.PageTextWhereInput | Prisma.PageTextWhereInput[]
  OR?: Prisma.PageTextWhereInput[]
  NOT?: Prisma.PageTextWhereInput | Prisma.PageTextWhereInput[]
  text?: Prisma.StringFilter<"PageText"> | string
}, "identifier">

export type PageTextOrderByWithAggregationInput = {
  identifier?: Prisma.SortOrder
  text?: Prisma.SortOrder
  _count?: Prisma.PageTextCountOrderByAggregateInput
  _max?: Prisma.PageTextMaxOrderByAggregateInput
  _min?: Prisma.PageTextMinOrderByAggregateInput
}

export type PageTextScalarWhereWithAggregatesInput = {
  AND?: Prisma.PageTextScalarWhereWithAggregatesInput | Prisma.PageTextScalarWhereWithAggregatesInput[]
  OR?: Prisma.PageTextScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PageTextScalarWhereWithAggregatesInput | Prisma.PageTextScalarWhereWithAggregatesInput[]
  identifier?: Prisma.StringWithAggregatesFilter<"PageText"> | string
  text?: Prisma.StringWithAggregatesFilter<"PageText"> | string
}

export type PageTextCreateInput = {
  identifier: string
  text?: string
}

export type PageTextUncheckedCreateInput = {
  identifier: string
  text?: string
}

export type PageTextUpdateInput = {
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PageTextUncheckedUpdateInput = {
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PageTextCreateManyInput = {
  identifier: string
  text?: string
}

export type PageTextUpdateManyMutationInput = {
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PageTextUncheckedUpdateManyInput = {
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PageTextCountOrderByAggregateInput = {
  identifier?: Prisma.SortOrder
  text?: Prisma.SortOrder
}

export type PageTextMaxOrderByAggregateInput = {
  identifier?: Prisma.SortOrder
  text?: Prisma.SortOrder
}

export type PageTextMinOrderByAggregateInput = {
  identifier?: Prisma.SortOrder
  text?: Prisma.SortOrder
}



export type PageTextSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  identifier?: boolean
  text?: boolean
}, ExtArgs["result"]["pageText"]>

export type PageTextSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  identifier?: boolean
  text?: boolean
}, ExtArgs["result"]["pageText"]>

export type PageTextSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  identifier?: boolean
  text?: boolean
}, ExtArgs["result"]["pageText"]>

export type PageTextSelectScalar = {
  identifier?: boolean
  text?: boolean
}

export type PageTextOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"identifier" | "text", ExtArgs["result"]["pageText"]>

export type $PageTextPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PageText"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    identifier: string
    text: string
  }, ExtArgs["result"]["pageText"]>
  composites: {}
}

export type PageTextGetPayload<S extends boolean | null | undefined | PageTextDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PageTextPayload, S>

export type PageTextCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PageTextFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PageTextCountAggregateInputType | true
  }

export interface PageTextDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PageText'], meta: { name: 'PageText' } }
  /**
   * Find zero or one PageText that matches the filter.
   * @param {PageTextFindUniqueArgs} args - Arguments to find a PageText
   * @example
   * // Get one PageText
   * const pageText = await prisma.pageText.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PageTextFindUniqueArgs>(args: Prisma.SelectSubset<T, PageTextFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PageTextClient<runtime.Types.Result.GetResult<Prisma.$PageTextPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PageText that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PageTextFindUniqueOrThrowArgs} args - Arguments to find a PageText
   * @example
   * // Get one PageText
   * const pageText = await prisma.pageText.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PageTextFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PageTextFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PageTextClient<runtime.Types.Result.GetResult<Prisma.$PageTextPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PageText that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageTextFindFirstArgs} args - Arguments to find a PageText
   * @example
   * // Get one PageText
   * const pageText = await prisma.pageText.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PageTextFindFirstArgs>(args?: Prisma.SelectSubset<T, PageTextFindFirstArgs<ExtArgs>>): Prisma.Prisma__PageTextClient<runtime.Types.Result.GetResult<Prisma.$PageTextPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PageText that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageTextFindFirstOrThrowArgs} args - Arguments to find a PageText
   * @example
   * // Get one PageText
   * const pageText = await prisma.pageText.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PageTextFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PageTextFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PageTextClient<runtime.Types.Result.GetResult<Prisma.$PageTextPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PageTexts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageTextFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PageTexts
   * const pageTexts = await prisma.pageText.findMany()
   * 
   * // Get first 10 PageTexts
   * const pageTexts = await prisma.pageText.findMany({ take: 10 })
   * 
   * // Only select the `identifier`
   * const pageTextWithIdentifierOnly = await prisma.pageText.findMany({ select: { identifier: true } })
   * 
   */
  findMany<T extends PageTextFindManyArgs>(args?: Prisma.SelectSubset<T, PageTextFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageTextPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PageText.
   * @param {PageTextCreateArgs} args - Arguments to create a PageText.
   * @example
   * // Create one PageText
   * const PageText = await prisma.pageText.create({
   *   data: {
   *     // ... data to create a PageText
   *   }
   * })
   * 
   */
  create<T extends PageTextCreateArgs>(args: Prisma.SelectSubset<T, PageTextCreateArgs<ExtArgs>>): Prisma.Prisma__PageTextClient<runtime.Types.Result.GetResult<Prisma.$PageTextPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PageTexts.
   * @param {PageTextCreateManyArgs} args - Arguments to create many PageTexts.
   * @example
   * // Create many PageTexts
   * const pageText = await prisma.pageText.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PageTextCreateManyArgs>(args?: Prisma.SelectSubset<T, PageTextCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PageTexts and returns the data saved in the database.
   * @param {PageTextCreateManyAndReturnArgs} args - Arguments to create many PageTexts.
   * @example
   * // Create many PageTexts
   * const pageText = await prisma.pageText.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PageTexts and only return the `identifier`
   * const pageTextWithIdentifierOnly = await prisma.pageText.createManyAndReturn({
   *   select: { identifier: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PageTextCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PageTextCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageTextPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PageText.
   * @param {PageTextDeleteArgs} args - Arguments to delete one PageText.
   * @example
   * // Delete one PageText
   * const PageText = await prisma.pageText.delete({
   *   where: {
   *     // ... filter to delete one PageText
   *   }
   * })
   * 
   */
  delete<T extends PageTextDeleteArgs>(args: Prisma.SelectSubset<T, PageTextDeleteArgs<ExtArgs>>): Prisma.Prisma__PageTextClient<runtime.Types.Result.GetResult<Prisma.$PageTextPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PageText.
   * @param {PageTextUpdateArgs} args - Arguments to update one PageText.
   * @example
   * // Update one PageText
   * const pageText = await prisma.pageText.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PageTextUpdateArgs>(args: Prisma.SelectSubset<T, PageTextUpdateArgs<ExtArgs>>): Prisma.Prisma__PageTextClient<runtime.Types.Result.GetResult<Prisma.$PageTextPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PageTexts.
   * @param {PageTextDeleteManyArgs} args - Arguments to filter PageTexts to delete.
   * @example
   * // Delete a few PageTexts
   * const { count } = await prisma.pageText.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PageTextDeleteManyArgs>(args?: Prisma.SelectSubset<T, PageTextDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PageTexts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageTextUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PageTexts
   * const pageText = await prisma.pageText.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PageTextUpdateManyArgs>(args: Prisma.SelectSubset<T, PageTextUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PageTexts and returns the data updated in the database.
   * @param {PageTextUpdateManyAndReturnArgs} args - Arguments to update many PageTexts.
   * @example
   * // Update many PageTexts
   * const pageText = await prisma.pageText.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PageTexts and only return the `identifier`
   * const pageTextWithIdentifierOnly = await prisma.pageText.updateManyAndReturn({
   *   select: { identifier: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PageTextUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PageTextUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageTextPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PageText.
   * @param {PageTextUpsertArgs} args - Arguments to update or create a PageText.
   * @example
   * // Update or create a PageText
   * const pageText = await prisma.pageText.upsert({
   *   create: {
   *     // ... data to create a PageText
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PageText we want to update
   *   }
   * })
   */
  upsert<T extends PageTextUpsertArgs>(args: Prisma.SelectSubset<T, PageTextUpsertArgs<ExtArgs>>): Prisma.Prisma__PageTextClient<runtime.Types.Result.GetResult<Prisma.$PageTextPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PageTexts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageTextCountArgs} args - Arguments to filter PageTexts to count.
   * @example
   * // Count the number of PageTexts
   * const count = await prisma.pageText.count({
   *   where: {
   *     // ... the filter for the PageTexts we want to count
   *   }
   * })
  **/
  count<T extends PageTextCountArgs>(
    args?: Prisma.Subset<T, PageTextCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PageTextCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PageText.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageTextAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PageTextAggregateArgs>(args: Prisma.Subset<T, PageTextAggregateArgs>): Prisma.PrismaPromise<GetPageTextAggregateType<T>>

  /**
   * Group by PageText.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageTextGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PageTextGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PageTextGroupByArgs['orderBy'] }
      : { orderBy?: PageTextGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PageTextGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPageTextGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PageText model
 */
readonly fields: PageTextFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PageText.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PageTextClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PageText model
 */
export interface PageTextFieldRefs {
  readonly identifier: Prisma.FieldRef<"PageText", 'String'>
  readonly text: Prisma.FieldRef<"PageText", 'String'>
}
    

// Custom InputTypes
/**
 * PageText findUnique
 */
export type PageTextFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
  /**
   * Filter, which PageText to fetch.
   */
  where: Prisma.PageTextWhereUniqueInput
}

/**
 * PageText findUniqueOrThrow
 */
export type PageTextFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
  /**
   * Filter, which PageText to fetch.
   */
  where: Prisma.PageTextWhereUniqueInput
}

/**
 * PageText findFirst
 */
export type PageTextFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
  /**
   * Filter, which PageText to fetch.
   */
  where?: Prisma.PageTextWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageTexts to fetch.
   */
  orderBy?: Prisma.PageTextOrderByWithRelationInput | Prisma.PageTextOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PageTexts.
   */
  cursor?: Prisma.PageTextWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageTexts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageTexts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PageTexts.
   */
  distinct?: Prisma.PageTextScalarFieldEnum | Prisma.PageTextScalarFieldEnum[]
}

/**
 * PageText findFirstOrThrow
 */
export type PageTextFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
  /**
   * Filter, which PageText to fetch.
   */
  where?: Prisma.PageTextWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageTexts to fetch.
   */
  orderBy?: Prisma.PageTextOrderByWithRelationInput | Prisma.PageTextOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PageTexts.
   */
  cursor?: Prisma.PageTextWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageTexts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageTexts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PageTexts.
   */
  distinct?: Prisma.PageTextScalarFieldEnum | Prisma.PageTextScalarFieldEnum[]
}

/**
 * PageText findMany
 */
export type PageTextFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
  /**
   * Filter, which PageTexts to fetch.
   */
  where?: Prisma.PageTextWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageTexts to fetch.
   */
  orderBy?: Prisma.PageTextOrderByWithRelationInput | Prisma.PageTextOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PageTexts.
   */
  cursor?: Prisma.PageTextWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageTexts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageTexts.
   */
  skip?: number
  distinct?: Prisma.PageTextScalarFieldEnum | Prisma.PageTextScalarFieldEnum[]
}

/**
 * PageText create
 */
export type PageTextCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
  /**
   * The data needed to create a PageText.
   */
  data: Prisma.XOR<Prisma.PageTextCreateInput, Prisma.PageTextUncheckedCreateInput>
}

/**
 * PageText createMany
 */
export type PageTextCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PageTexts.
   */
  data: Prisma.PageTextCreateManyInput | Prisma.PageTextCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PageText createManyAndReturn
 */
export type PageTextCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
  /**
   * The data used to create many PageTexts.
   */
  data: Prisma.PageTextCreateManyInput | Prisma.PageTextCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PageText update
 */
export type PageTextUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
  /**
   * The data needed to update a PageText.
   */
  data: Prisma.XOR<Prisma.PageTextUpdateInput, Prisma.PageTextUncheckedUpdateInput>
  /**
   * Choose, which PageText to update.
   */
  where: Prisma.PageTextWhereUniqueInput
}

/**
 * PageText updateMany
 */
export type PageTextUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PageTexts.
   */
  data: Prisma.XOR<Prisma.PageTextUpdateManyMutationInput, Prisma.PageTextUncheckedUpdateManyInput>
  /**
   * Filter which PageTexts to update
   */
  where?: Prisma.PageTextWhereInput
  /**
   * Limit how many PageTexts to update.
   */
  limit?: number
}

/**
 * PageText updateManyAndReturn
 */
export type PageTextUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
  /**
   * The data used to update PageTexts.
   */
  data: Prisma.XOR<Prisma.PageTextUpdateManyMutationInput, Prisma.PageTextUncheckedUpdateManyInput>
  /**
   * Filter which PageTexts to update
   */
  where?: Prisma.PageTextWhereInput
  /**
   * Limit how many PageTexts to update.
   */
  limit?: number
}

/**
 * PageText upsert
 */
export type PageTextUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
  /**
   * The filter to search for the PageText to update in case it exists.
   */
  where: Prisma.PageTextWhereUniqueInput
  /**
   * In case the PageText found by the `where` argument doesn't exist, create a new PageText with this data.
   */
  create: Prisma.XOR<Prisma.PageTextCreateInput, Prisma.PageTextUncheckedCreateInput>
  /**
   * In case the PageText was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PageTextUpdateInput, Prisma.PageTextUncheckedUpdateInput>
}

/**
 * PageText delete
 */
export type PageTextDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
  /**
   * Filter which PageText to delete.
   */
  where: Prisma.PageTextWhereUniqueInput
}

/**
 * PageText deleteMany
 */
export type PageTextDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PageTexts to delete
   */
  where?: Prisma.PageTextWhereInput
  /**
   * Limit how many PageTexts to delete.
   */
  limit?: number
}

/**
 * PageText without action
 */
export type PageTextDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageText
   */
  select?: Prisma.PageTextSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageText
   */
  omit?: Prisma.PageTextOmit<ExtArgs> | null
}
