
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `PageImage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PageImage
 * 
 */
export type PageImageModel = runtime.Types.Result.DefaultSelection<Prisma.$PageImagePayload>

export type AggregatePageImage = {
  _count: PageImageCountAggregateOutputType | null
  _min: PageImageMinAggregateOutputType | null
  _max: PageImageMaxAggregateOutputType | null
}

export type PageImageMinAggregateOutputType = {
  identifier: string | null
  aboutImage: string | null
}

export type PageImageMaxAggregateOutputType = {
  identifier: string | null
  aboutImage: string | null
}

export type PageImageCountAggregateOutputType = {
  identifier: number
  aboutImage: number
  _all: number
}


export type PageImageMinAggregateInputType = {
  identifier?: true
  aboutImage?: true
}

export type PageImageMaxAggregateInputType = {
  identifier?: true
  aboutImage?: true
}

export type PageImageCountAggregateInputType = {
  identifier?: true
  aboutImage?: true
  _all?: true
}

export type PageImageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PageImage to aggregate.
   */
  where?: Prisma.PageImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageImages to fetch.
   */
  orderBy?: Prisma.PageImageOrderByWithRelationInput | Prisma.PageImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PageImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PageImages
  **/
  _count?: true | PageImageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PageImageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PageImageMaxAggregateInputType
}

export type GetPageImageAggregateType<T extends PageImageAggregateArgs> = {
      [P in keyof T & keyof AggregatePageImage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePageImage[P]>
    : Prisma.GetScalarType<T[P], AggregatePageImage[P]>
}




export type PageImageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PageImageWhereInput
  orderBy?: Prisma.PageImageOrderByWithAggregationInput | Prisma.PageImageOrderByWithAggregationInput[]
  by: Prisma.PageImageScalarFieldEnum[] | Prisma.PageImageScalarFieldEnum
  having?: Prisma.PageImageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PageImageCountAggregateInputType | true
  _min?: PageImageMinAggregateInputType
  _max?: PageImageMaxAggregateInputType
}

export type PageImageGroupByOutputType = {
  identifier: string
  aboutImage: string
  _count: PageImageCountAggregateOutputType | null
  _min: PageImageMinAggregateOutputType | null
  _max: PageImageMaxAggregateOutputType | null
}

type GetPageImageGroupByPayload<T extends PageImageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PageImageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PageImageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PageImageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PageImageGroupByOutputType[P]>
      }
    >
  >



export type PageImageWhereInput = {
  AND?: Prisma.PageImageWhereInput | Prisma.PageImageWhereInput[]
  OR?: Prisma.PageImageWhereInput[]
  NOT?: Prisma.PageImageWhereInput | Prisma.PageImageWhereInput[]
  identifier?: Prisma.StringFilter<"PageImage"> | string
  aboutImage?: Prisma.StringFilter<"PageImage"> | string
}

export type PageImageOrderByWithRelationInput = {
  identifier?: Prisma.SortOrder
  aboutImage?: Prisma.SortOrder
}

export type PageImageWhereUniqueInput = Prisma.AtLeast<{
  identifier?: string
  AND?: Prisma.PageImageWhereInput | Prisma.PageImageWhereInput[]
  OR?: Prisma.PageImageWhereInput[]
  NOT?: Prisma.PageImageWhereInput | Prisma.PageImageWhereInput[]
  aboutImage?: Prisma.StringFilter<"PageImage"> | string
}, "identifier">

export type PageImageOrderByWithAggregationInput = {
  identifier?: Prisma.SortOrder
  aboutImage?: Prisma.SortOrder
  _count?: Prisma.PageImageCountOrderByAggregateInput
  _max?: Prisma.PageImageMaxOrderByAggregateInput
  _min?: Prisma.PageImageMinOrderByAggregateInput
}

export type PageImageScalarWhereWithAggregatesInput = {
  AND?: Prisma.PageImageScalarWhereWithAggregatesInput | Prisma.PageImageScalarWhereWithAggregatesInput[]
  OR?: Prisma.PageImageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PageImageScalarWhereWithAggregatesInput | Prisma.PageImageScalarWhereWithAggregatesInput[]
  identifier?: Prisma.StringWithAggregatesFilter<"PageImage"> | string
  aboutImage?: Prisma.StringWithAggregatesFilter<"PageImage"> | string
}

export type PageImageCreateInput = {
  identifier: string
  aboutImage?: string
}

export type PageImageUncheckedCreateInput = {
  identifier: string
  aboutImage?: string
}

export type PageImageUpdateInput = {
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  aboutImage?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PageImageUncheckedUpdateInput = {
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  aboutImage?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PageImageCreateManyInput = {
  identifier: string
  aboutImage?: string
}

export type PageImageUpdateManyMutationInput = {
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  aboutImage?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PageImageUncheckedUpdateManyInput = {
  identifier?: Prisma.StringFieldUpdateOperationsInput | string
  aboutImage?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PageImageCountOrderByAggregateInput = {
  identifier?: Prisma.SortOrder
  aboutImage?: Prisma.SortOrder
}

export type PageImageMaxOrderByAggregateInput = {
  identifier?: Prisma.SortOrder
  aboutImage?: Prisma.SortOrder
}

export type PageImageMinOrderByAggregateInput = {
  identifier?: Prisma.SortOrder
  aboutImage?: Prisma.SortOrder
}



export type PageImageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  identifier?: boolean
  aboutImage?: boolean
}, ExtArgs["result"]["pageImage"]>

export type PageImageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  identifier?: boolean
  aboutImage?: boolean
}, ExtArgs["result"]["pageImage"]>

export type PageImageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  identifier?: boolean
  aboutImage?: boolean
}, ExtArgs["result"]["pageImage"]>

export type PageImageSelectScalar = {
  identifier?: boolean
  aboutImage?: boolean
}

export type PageImageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"identifier" | "aboutImage", ExtArgs["result"]["pageImage"]>

export type $PageImagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PageImage"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    identifier: string
    aboutImage: string
  }, ExtArgs["result"]["pageImage"]>
  composites: {}
}

export type PageImageGetPayload<S extends boolean | null | undefined | PageImageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PageImagePayload, S>

export type PageImageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PageImageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PageImageCountAggregateInputType | true
  }

export interface PageImageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PageImage'], meta: { name: 'PageImage' } }
  /**
   * Find zero or one PageImage that matches the filter.
   * @param {PageImageFindUniqueArgs} args - Arguments to find a PageImage
   * @example
   * // Get one PageImage
   * const pageImage = await prisma.pageImage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PageImageFindUniqueArgs>(args: Prisma.SelectSubset<T, PageImageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PageImageClient<runtime.Types.Result.GetResult<Prisma.$PageImagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PageImage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PageImageFindUniqueOrThrowArgs} args - Arguments to find a PageImage
   * @example
   * // Get one PageImage
   * const pageImage = await prisma.pageImage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PageImageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PageImageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PageImageClient<runtime.Types.Result.GetResult<Prisma.$PageImagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PageImage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageImageFindFirstArgs} args - Arguments to find a PageImage
   * @example
   * // Get one PageImage
   * const pageImage = await prisma.pageImage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PageImageFindFirstArgs>(args?: Prisma.SelectSubset<T, PageImageFindFirstArgs<ExtArgs>>): Prisma.Prisma__PageImageClient<runtime.Types.Result.GetResult<Prisma.$PageImagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PageImage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageImageFindFirstOrThrowArgs} args - Arguments to find a PageImage
   * @example
   * // Get one PageImage
   * const pageImage = await prisma.pageImage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PageImageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PageImageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PageImageClient<runtime.Types.Result.GetResult<Prisma.$PageImagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PageImages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageImageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PageImages
   * const pageImages = await prisma.pageImage.findMany()
   * 
   * // Get first 10 PageImages
   * const pageImages = await prisma.pageImage.findMany({ take: 10 })
   * 
   * // Only select the `identifier`
   * const pageImageWithIdentifierOnly = await prisma.pageImage.findMany({ select: { identifier: true } })
   * 
   */
  findMany<T extends PageImageFindManyArgs>(args?: Prisma.SelectSubset<T, PageImageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageImagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PageImage.
   * @param {PageImageCreateArgs} args - Arguments to create a PageImage.
   * @example
   * // Create one PageImage
   * const PageImage = await prisma.pageImage.create({
   *   data: {
   *     // ... data to create a PageImage
   *   }
   * })
   * 
   */
  create<T extends PageImageCreateArgs>(args: Prisma.SelectSubset<T, PageImageCreateArgs<ExtArgs>>): Prisma.Prisma__PageImageClient<runtime.Types.Result.GetResult<Prisma.$PageImagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PageImages.
   * @param {PageImageCreateManyArgs} args - Arguments to create many PageImages.
   * @example
   * // Create many PageImages
   * const pageImage = await prisma.pageImage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PageImageCreateManyArgs>(args?: Prisma.SelectSubset<T, PageImageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PageImages and returns the data saved in the database.
   * @param {PageImageCreateManyAndReturnArgs} args - Arguments to create many PageImages.
   * @example
   * // Create many PageImages
   * const pageImage = await prisma.pageImage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PageImages and only return the `identifier`
   * const pageImageWithIdentifierOnly = await prisma.pageImage.createManyAndReturn({
   *   select: { identifier: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PageImageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PageImageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageImagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PageImage.
   * @param {PageImageDeleteArgs} args - Arguments to delete one PageImage.
   * @example
   * // Delete one PageImage
   * const PageImage = await prisma.pageImage.delete({
   *   where: {
   *     // ... filter to delete one PageImage
   *   }
   * })
   * 
   */
  delete<T extends PageImageDeleteArgs>(args: Prisma.SelectSubset<T, PageImageDeleteArgs<ExtArgs>>): Prisma.Prisma__PageImageClient<runtime.Types.Result.GetResult<Prisma.$PageImagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PageImage.
   * @param {PageImageUpdateArgs} args - Arguments to update one PageImage.
   * @example
   * // Update one PageImage
   * const pageImage = await prisma.pageImage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PageImageUpdateArgs>(args: Prisma.SelectSubset<T, PageImageUpdateArgs<ExtArgs>>): Prisma.Prisma__PageImageClient<runtime.Types.Result.GetResult<Prisma.$PageImagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PageImages.
   * @param {PageImageDeleteManyArgs} args - Arguments to filter PageImages to delete.
   * @example
   * // Delete a few PageImages
   * const { count } = await prisma.pageImage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PageImageDeleteManyArgs>(args?: Prisma.SelectSubset<T, PageImageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PageImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageImageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PageImages
   * const pageImage = await prisma.pageImage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PageImageUpdateManyArgs>(args: Prisma.SelectSubset<T, PageImageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PageImages and returns the data updated in the database.
   * @param {PageImageUpdateManyAndReturnArgs} args - Arguments to update many PageImages.
   * @example
   * // Update many PageImages
   * const pageImage = await prisma.pageImage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PageImages and only return the `identifier`
   * const pageImageWithIdentifierOnly = await prisma.pageImage.updateManyAndReturn({
   *   select: { identifier: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PageImageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PageImageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageImagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PageImage.
   * @param {PageImageUpsertArgs} args - Arguments to update or create a PageImage.
   * @example
   * // Update or create a PageImage
   * const pageImage = await prisma.pageImage.upsert({
   *   create: {
   *     // ... data to create a PageImage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PageImage we want to update
   *   }
   * })
   */
  upsert<T extends PageImageUpsertArgs>(args: Prisma.SelectSubset<T, PageImageUpsertArgs<ExtArgs>>): Prisma.Prisma__PageImageClient<runtime.Types.Result.GetResult<Prisma.$PageImagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PageImages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageImageCountArgs} args - Arguments to filter PageImages to count.
   * @example
   * // Count the number of PageImages
   * const count = await prisma.pageImage.count({
   *   where: {
   *     // ... the filter for the PageImages we want to count
   *   }
   * })
  **/
  count<T extends PageImageCountArgs>(
    args?: Prisma.Subset<T, PageImageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PageImageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PageImage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageImageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PageImageAggregateArgs>(args: Prisma.Subset<T, PageImageAggregateArgs>): Prisma.PrismaPromise<GetPageImageAggregateType<T>>

  /**
   * Group by PageImage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageImageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PageImageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PageImageGroupByArgs['orderBy'] }
      : { orderBy?: PageImageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PageImageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPageImageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PageImage model
 */
readonly fields: PageImageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PageImage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PageImageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PageImage model
 */
export interface PageImageFieldRefs {
  readonly identifier: Prisma.FieldRef<"PageImage", 'String'>
  readonly aboutImage: Prisma.FieldRef<"PageImage", 'String'>
}
    

// Custom InputTypes
/**
 * PageImage findUnique
 */
export type PageImageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
  /**
   * Filter, which PageImage to fetch.
   */
  where: Prisma.PageImageWhereUniqueInput
}

/**
 * PageImage findUniqueOrThrow
 */
export type PageImageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
  /**
   * Filter, which PageImage to fetch.
   */
  where: Prisma.PageImageWhereUniqueInput
}

/**
 * PageImage findFirst
 */
export type PageImageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
  /**
   * Filter, which PageImage to fetch.
   */
  where?: Prisma.PageImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageImages to fetch.
   */
  orderBy?: Prisma.PageImageOrderByWithRelationInput | Prisma.PageImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PageImages.
   */
  cursor?: Prisma.PageImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PageImages.
   */
  distinct?: Prisma.PageImageScalarFieldEnum | Prisma.PageImageScalarFieldEnum[]
}

/**
 * PageImage findFirstOrThrow
 */
export type PageImageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
  /**
   * Filter, which PageImage to fetch.
   */
  where?: Prisma.PageImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageImages to fetch.
   */
  orderBy?: Prisma.PageImageOrderByWithRelationInput | Prisma.PageImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PageImages.
   */
  cursor?: Prisma.PageImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageImages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PageImages.
   */
  distinct?: Prisma.PageImageScalarFieldEnum | Prisma.PageImageScalarFieldEnum[]
}

/**
 * PageImage findMany
 */
export type PageImageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
  /**
   * Filter, which PageImages to fetch.
   */
  where?: Prisma.PageImageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageImages to fetch.
   */
  orderBy?: Prisma.PageImageOrderByWithRelationInput | Prisma.PageImageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PageImages.
   */
  cursor?: Prisma.PageImageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageImages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageImages.
   */
  skip?: number
  distinct?: Prisma.PageImageScalarFieldEnum | Prisma.PageImageScalarFieldEnum[]
}

/**
 * PageImage create
 */
export type PageImageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
  /**
   * The data needed to create a PageImage.
   */
  data: Prisma.XOR<Prisma.PageImageCreateInput, Prisma.PageImageUncheckedCreateInput>
}

/**
 * PageImage createMany
 */
export type PageImageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PageImages.
   */
  data: Prisma.PageImageCreateManyInput | Prisma.PageImageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PageImage createManyAndReturn
 */
export type PageImageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
  /**
   * The data used to create many PageImages.
   */
  data: Prisma.PageImageCreateManyInput | Prisma.PageImageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PageImage update
 */
export type PageImageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
  /**
   * The data needed to update a PageImage.
   */
  data: Prisma.XOR<Prisma.PageImageUpdateInput, Prisma.PageImageUncheckedUpdateInput>
  /**
   * Choose, which PageImage to update.
   */
  where: Prisma.PageImageWhereUniqueInput
}

/**
 * PageImage updateMany
 */
export type PageImageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PageImages.
   */
  data: Prisma.XOR<Prisma.PageImageUpdateManyMutationInput, Prisma.PageImageUncheckedUpdateManyInput>
  /**
   * Filter which PageImages to update
   */
  where?: Prisma.PageImageWhereInput
  /**
   * Limit how many PageImages to update.
   */
  limit?: number
}

/**
 * PageImage updateManyAndReturn
 */
export type PageImageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
  /**
   * The data used to update PageImages.
   */
  data: Prisma.XOR<Prisma.PageImageUpdateManyMutationInput, Prisma.PageImageUncheckedUpdateManyInput>
  /**
   * Filter which PageImages to update
   */
  where?: Prisma.PageImageWhereInput
  /**
   * Limit how many PageImages to update.
   */
  limit?: number
}

/**
 * PageImage upsert
 */
export type PageImageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
  /**
   * The filter to search for the PageImage to update in case it exists.
   */
  where: Prisma.PageImageWhereUniqueInput
  /**
   * In case the PageImage found by the `where` argument doesn't exist, create a new PageImage with this data.
   */
  create: Prisma.XOR<Prisma.PageImageCreateInput, Prisma.PageImageUncheckedCreateInput>
  /**
   * In case the PageImage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PageImageUpdateInput, Prisma.PageImageUncheckedUpdateInput>
}

/**
 * PageImage delete
 */
export type PageImageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
  /**
   * Filter which PageImage to delete.
   */
  where: Prisma.PageImageWhereUniqueInput
}

/**
 * PageImage deleteMany
 */
export type PageImageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PageImages to delete
   */
  where?: Prisma.PageImageWhereInput
  /**
   * Limit how many PageImages to delete.
   */
  limit?: number
}

/**
 * PageImage without action
 */
export type PageImageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageImage
   */
  select?: Prisma.PageImageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageImage
   */
  omit?: Prisma.PageImageOmit<ExtArgs> | null
}
