-- AlterTable
ALTER TABLE "Artist" ADD COLUMN     "bio" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "color1" TEXT NOT NULL DEFAULT '#000000',
ADD COLUMN     "color2" TEXT NOT NULL DEFAULT '#000000',
ADD COLUMN     "image" TEXT NOT NULL DEFAULT '';
